<?php

/*
 * DoubleScroll version number
 */
define(DS_VERSION, '0.3');

/**
 * Implements hook_library().
 */
function doublescroll_library() {
    $libraries['doublescroll'] = array(
        'title' => 'DoubleScroll',
        'website' => 'https://github.com/sniku/jQuery-doubleScroll',
        'version' => DS_VERSION,
        'js' => array(
            drupal_get_path('module', 'doublescroll') . '/js/jquery.doubleScroll.js' => array()
        )
    );
    return $libraries;
}

/**
 * Implements hook_menu().
 */
function doublescroll_menu() {
    $items['admin/config/user-interface/doublescroll'] = array(
        'title' => 'DoubleScroll',
        'description' => 'Adds an additional scroll on top of very wide table.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('doublescroll_settings_form'),
        'access arguments' => array('administer doublescroll'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'doublescroll.admin.inc',
    );

    return $items;
}

/**
 * Implements hook_permission().
 */
function doublescroll_permission() {
    return array(
        'administer doublescroll' => array(
            'title' => t('Administer DoubleScroll'),
            'description' => t('Administer DoubleScroll settings.'),
        ),
    );
}

/**
 * Implements hook_init().
 */
function doublescroll_init() {
    $selector = variable_get('doublescroll_selector', '.doublescroll');
    $js = "$(document).ready(function(){\$('" . $selector . "').doubleScroll();});";
    drupal_add_js($js, 'inline');
}
